### ISSUE TITLE
werfault  why?

### ISSUE THREAD

**Issue by xiaotsai** [Konis-Bros/Espio#2]
How do you open the werfault.exe for inject and why U choose that

**Comment by dkonis** [comment]
Hi @xiaotsai,
we chose to inject to the werfault.exe process because windows expects it to open tcp connections (for error reporting).

As for how do we open it,
we call RtlCreateProcessParameters and RtlCreateUserProcess as can be viewed in main.cpp:
https://github.com/Konis-Bros/Espio/blob/main/loader/Espio/main.cpp

**Comment by xiaotsai** [comment]
OK thank you
